services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  ExdropCommon\SharedCodeBundle\Shared\Application\Service\CQRS\CommandBus: ~

  ExdropCommon\SharedCodeBundle\Shared\Application\Service\CQRS\QueryBus: ~

  ExdropCommon\SharedCodeBundle\Shared\Application\Service\CQRS\EventBus: ~

  ExdropCommon\SharedCodeBundle\Shared\Application\Service\CQRS\CommandBusInterface: '@ExdropCommon\SharedCodeBundle\Shared\Application\Service\CQRS\CommandBus'

  ExdropCommon\SharedCodeBundle\Shared\Application\Service\CQRS\QueryBusInterface: '@ExdropCommon\SharedCodeBundle\Shared\Application\Service\CQRS\QueryBus'

  ExdropCommon\SharedCodeBundle\Shared\Application\Service\CQRS\EventBusInterface: '@ExdropCommon\SharedCodeBundle\Shared\Application\Service\CQRS\EventBus'

