services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  ExdropCommon\SharedCodeBundle\Application\Service\CommandBus: ~

  ExdropCommon\SharedCodeBundle\Application\Service\QueryBus: ~

  ExdropCommon\SharedCodeBundle\Application\Service\EventBus: ~

  ExdropCommon\SharedCodeBundle\Shared\Application\Service\CQRS\CommandBusInterface: '@ExdropCQRS\SharedCodeBundle\Application\Service\CommandBus'

  ExdropCommon\SharedCodeBundle\Application\Service\CQRS\QueryBusInterface: '@ExdropCQRS\SharedCodeBundle\Application\Service\QueryBus'

  ExdropCommon\SharedCodeBundle\Application\Service\CQRS\EventBusInterface: '@ExdropCQRS\SharedCodeBundle\Application\Service\EventBus'

