services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  ExdropCQRS\Application\Service\CommandBus: ~

  ExdropCQRS\Application\Service\QueryBus: ~

  ExdropCQRS\Application\Service\EventBus: ~

  ExdropCQRS\Application\Service\CommandBusInterface: '@ExdropCQRS\Application\Service\CommandBus'

  ExdropCQRS\Application\Service\QueryBusInterface: '@ExdropCQRS\Application\Service\QueryBus'

  ExdropCQRS\Application\Service\EventBusInterface: '@ExdropCQRS\Application\Service\EventBus'

